Cambios solicitados
elagarrigue/AyDS21-AK-Hera3 pull request #1
Opened 2021-05-04 02:42 UTC by santiagopardal

Añadida release_date_precision, modificada la base de datos y mostrada la fecha como se solicitó

2021-05-04 12:45 UTC, elagarrigue requested changes
Bien en general, falta solucionar OC.

2021-05-04 12:45 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/model/entities/SpotifySong.kt
> +) : Song
Este formato no se corresponde con el resto de las clases, revertir

2021-05-04 12:45 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +                null
Indentación denuevo. Checkeen que tengan los mismos settings (Settings -> Editor -> Code Style -> Kotlin -> Indent 4, Continuation Indent 8)

2021-05-04 12:45 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/view/SongDescriptionHelperImpl.kt
> +internal class SongDescriptionHelperImpl (private val dateHelper: ReleaseDateStringHelper = ReleaseDateStringHelperImpl()) : SongDescriptionHelper {
No crear instancias de la implementación en el constructor,  no cumple con inversión de dependencias. Crear la instancia en la clase `module`

2021-05-04 12:45 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/view/ReleaseDateStringHelperImpl.kt
> +    fun getReleaseDateDescriptionText(song: Song = EmptySong): String
El nombre es algo genérico. Mejor algo como SongToReleaseDateStringMapper, con una función map

2021-05-04 12:45 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/view/ReleaseDateStringHelperImpl.kt
> +internal class ReleaseDateStringHelperImpl: ReleaseDateStringHelper {
Ahora esta clase tiene 3 responsabilidades... Para solucionarlo:
- Implementar 3 clases que implementen `SongToReleaseDateStringMapper` (el viejo `ReleaseDateStringHelper`)
- Implementar un Factory que dado un objeto `Song` retorne un objeto `SongToReleaseDateStringMapper`
- Inyectar en factory en description helper.

Y una mejora, al usar un Factory, puden crear los mappers con el objeto song, por lo que no sería necesario el parámetro en map(). Algo así:

```
interface SongToReleaseDateStringMapper {
   fun map()
}

internal SongToDayReleaseDateStringMapper (private val song: Song) : SongToReleaseDateStringMapper { ... }
```
Y el factory tendría la lógica de crear los mappers en base al song:

```
    fun get(song: Song) : SongToReleaseDateStringMapper =
       = when (song.releaseDatePrecision) {
            "day" -> SongToDayReleaseDateStringMapper(song)
            "month" -> SongToMonthReleaseDateStringMapper(song)  ...
        
```

Los factories escapan a la regla de "crear las instancias en los modules", ya que de por sí su única responsabilidad es crear instancias. En ese sentido, los modules son factories.

2021-05-04 12:45 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/view/ReleaseDateStringHelperImpl.kt
> +                else -> "Not valid"
No es un buen resultado. Si sabemos que es imposible que entre por este caso y el `when` nos obliga al else, minimamente disparar una excepción. En este caso no estamos seguros, `song.releaseDate` es una mejor opción.

2021-05-04 13:37 UTC, santiagopardal commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/model/entities/SpotifySong.kt
> +) : Song
Emma disculpame, con el formato te referis a lo mismo que [abajo](https://github.com/elagarrigue/AyDS21-AK-Hera3/pull/1#discussion_r625744746) ¿no?

2021-05-04 14:38 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/model/entities/SpotifySong.kt
> +) : Song
sisi. No deberian haber cambios en esas lineas

2021-05-06 12:49 UTC, elagarrigue requested changes
Últimos detalles

2021-05-06 12:49 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/view/SongToReleaseDateStringMapperFactory.kt
> +}
Mejor una interfaz

2021-05-06 12:49 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/view/SongToDayReleaseDateStringMapper.kt
> +        return "${dateSplit[2]}/${dateSplit[1]}/${dateSplit[0]}"
Es poco clean, hay que hacer un mapeo mental. Mejor definir variables intermedias 
```
val day = dateSplit[2]
...
return "$day/$month/$year "
```

2021-05-06 12:49 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/view/SongToDayReleaseDateStringMapper.kt
> +        val month = arrayOf("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
Mejor definir el array como propiedad de la clase.

2021-05-06 12:49 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/home/view/SongToDayReleaseDateStringMapper.kt
> +        return month[dateSplit[1].toInt() - 1] + ", " + dateSplit[0]
Denuevo el mapeo mental, y usar el valor - 1 de índice en el arreglo es un smell.   Una mejor opción sería un hash map, número a string mes, o incluso una función con el when, en sí no hace falta la estructura de datos.

2021-05-07 01:47 UTC, elagarrigue approved these changes
Ahí quedó :+1:

2021-05-07 01:51 UTC, merged