Etapa final
elagarrigue/AyDS21-AK-Hera3 pull request #5
Opened 2021-07-05 20:48 UTC by santiagopardal

Implementación de broker con proxies e incorporación de servicios externos, en conjunto con cambios acordes a la vista.

2021-07-06 12:05 UTC, elagarrigue requested changes
No están bien agregados los submódulos de apolo 1 y zeus 2, no deberían estar las classes de las librerías en el repo, sino los submódulos de git

Diagrama: El broker conoce una lista de proxies, falta esa notación

2021-07-06 12:05 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +    private fun updatePanesVisibility(results: Boolean){
`results` no es un nombre claro para un bollean

2021-07-06 12:05 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +        for ((i, e) in cards.withIndex())
`e` no es un nombre claro para una card

2021-07-06 12:05 UTC, elagarrigue commented on AK Hera/app/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +
`e`

2021-07-06 16:15 UTC, alanrychert commented on AK Hera/app/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +
Cambiado a "card"

2021-07-06 16:16 UTC, alanrychert commented on AK Hera/app/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +        for ((i, e) in cards.withIndex())
Cambiado a "card"

2021-07-06 16:39 UTC, alanrychert commented on AK Hera/app/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +    private fun updatePanesVisibility(results: Boolean){
Cambiado a "cardsAvailable"

2021-07-07 12:28 UTC, elagarrigue requested changes
Ejecución :
- Faltan las imágenes de las fuentes
- Sería bueno agregar un progress bar para indicar tiempo de carga
- La búsqueda "epor" genera un crash en more details

2021-07-09 15:32 UTC, elagarrigue approved these changes
Excelente, quedó muy bien 🙌🏽

2021-07-09 15:32 UTC, merged